### ISSUE TITLE
[Docs] organization 대문 소개 자료 만들기

### ISSUE THREAD

**Issue by youngmin-gwon** [PLAIF-dev/.github#8]
```[tasklist]
### Tasks
- [ ] https://github.com/PLAIF-dev/.github/issues/9#issue-1782054213
- [ ] https://github.com/PLAIF-dev/.github/issues/13#issue-1782179194
- [ ] https://github.com/PLAIF-dev/.github/issues/11
```

**Comment by powerstrong** [comment]
굿굿!

**Comment by youngmin-gwon** [comment]
@powerstrong 
대문 소개 자료 초안에 필요한 사항이 모두 완료되었으므로 issue를 닫습니다.
